### ISSUE TITLE
How to make custom menus, like calling formulas, allow users to pass parameters？

### ISSUE THREAD

**Issue by phpsxg** [pyxll/pyxll-examples#10]
How to make custom menus, like calling formulas, allow users to pass parameters？

![屏幕截图 2022-06-21 140714](https://user-images.githubusercontent.com/19278211/174729330-f4b017e6-48b5-4406-8854-8960c75da59c.png)

![屏幕截图 2022-06-21 140754](https://user-images.githubusercontent.com/19278211/174729334-25a3283f-39e2-42c8-9b44-594c9a876df2.png)

How to click hello to pass parameters?
THX!

**Comment by tonyroberts** [comment]
Hi! Thanks for also emailing your issue through to PyXLL support, that's a better channel for questions like this :) I will close this issue now and if you need any more help then please reach out to our support directly.
