### ISSUE TITLE
What is the syntax to use the Excel SolverOK command from pyxll

### ISSUE THREAD

**Issue by SDIdo** [pyxll/pyxll-examples#9]
**This is what I want to run in Excel from a python script:**

```
SolverOk
SetCell := "$O$3", MaxMinVal := 2, ValueOf := 0, ByChange := "$J$3:$K$3", _
Engine := 3, EngineDesc := "Evolutionary"
SolverSolve
```

After searching for a long time I have not found a suitable pyxll API to communicate this VBA script to Excel.

Note: Due to security issues I cannot use xl.run('vba_script')

However, this API works:

```
from win32com.client.gencache import EnsureDispatch
import pythoncom

xl = EnsureDispatch("Excel.Application", pythoncom.CoInitialize())
wb = xl.Workbooks.Open(Filename=r"Test.xlsx")

xl.Range("A1:B1").Value = "Worked"
```

So I am looking for an api similar in spirit to the following:

```
from win32com.client import Dispatch
x1 = Dispatch('Excel.Application')
workbook = x1.Workbooks.Open(r"Test2.xlsx")

x1.SolverOk()
x1.SetCell("$O$3")
x1.MaxMinVal("2")
x1.ValueOf("0")
x1.ByChange("$J$3:$K$3")
x1.Engine("3")
x1.EngineDesc("Evolutionary")
x1.SolverSolve()
```

Is there a support for this in pyxll?

Best,

**Comment by tonyroberts** [comment]
Please can you contact PyXLL support for support requests instead of rasing an issue on github. Thanks!
